import React from "react";
import CartPage from "./CartPage";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Cart | My Shop",
    description: "Generated by create next app",
};

const Cart = () => {
    return (
        <div className="container max-w-324 mx-auto">
            <CartPage />
        </div>
    );
};

export default Cart;
