import React from "react";
import CheckoutPage from "./CheckoutPage";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Checkout | My Shop",
    description: "Generated by create next app",
};

const Checkout = () => {
    return (
        <div className="container mx-auto">
            <CheckoutPage />
        </div>
    );
};

export default Checkout;
