import React from "react";
import CheckoutPage from "./CheckoutPage";
import { Metadata } from "next";
import PrivateRoute from "../components/PrivetRoute";

export const metadata: Metadata = {
    title: "Checkout | My Shop",
    description: "Generated by create next app",
};

const Checkout = () => {
    return (
        <div className="container max-w-324 mx-auto">
            <PrivateRoute>
                <CheckoutPage />
            </PrivateRoute>
        </div>
    );
};

export default Checkout;
