import React from "react";
import Banner from "../components/Home/Banner";
import CategoryBottom from "../components/Home/CategoryBottom";
import ShopProducts from "../components/ShopProducts";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Shop | My Shop",
    description: "Generated by create next app",
};

export default function page() {
    return (
        <>
            <Banner />
            <ShopProducts />
            <CategoryBottom />
        </>
    );
}
