import { Metadata } from "next";
import React from "react";
import MyOrders from "./MyOrders";

export const metadata: Metadata = {
    title: "My Orders | Dashboard",
    description: "Generated by create next app",
};

const page = () => {
    return (
        <>
            <MyOrders/>
        </>
    );
};

export default page;
